# Generated by Django 4.2.27 on 2025-12-24 05:34

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0095_groupsitepermission'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True)),
                ('steps', wagtail.fields.StreamField([('step', 10)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Unique ID for this step (e.g. 'router-check')"}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {}), 5: ('wagtail.blocks.StreamBlock', [[('text', 2), ('image', 3), ('video', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': 'Button text'}), 7: ('wagtail.blocks.CharBlock', (), {'help_text': 'ID of the next step. Leave empty to end.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 6), ('next_step_id', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {}), 10: ('wagtail.blocks.StructBlock', [[('step_id', 0), ('title', 1), ('content', 5), ('options', 9)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
