# Generated by Django 4.2.27 on 2025-12-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tutorialpage_delete_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialpage',
            name='flow_graph',
            field=models.JSONField(blank=True, help_text='Stores the flow editor graph data (nodes, positions)', null=True),
        ),
    ]
